[theme]
base = "light"
primaryColor = "#0E3B3E"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F5F7F7"
textColor = "#1A1F1F"

[server]
headless = true
runOnSave = false

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"
