[theme]
base = "light"
primaryColor = "#10243D"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F4F6F9"
textColor = "#1B1F24"

[server]
headless = true
runOnSave = false

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"
